<a href="https://colab.research.google.com/github/atqaamir/PriWorld-Privacy-Policy-Analysis/blob/hierarchical_multilabel_classification/hierarchical_multilabel_classifiers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install lxml

import bs4
import bs4.builder._lxml
bs4.builder.register_treebuilders_from(bs4.builder._lxml)


In [4]:
import bs4
import keras
from google.colab import files
from __future__ import print_function
from keras.preprocessing.image import ImageDataGenerator
from keras.layers import Conv2D, MaxPooling2D , Conv2DTranspose#, Conv2DTranspose
from keras.utils import np_utils
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Flatten, LSTM, Conv1D, MaxPooling1D, Dropout, Activation
from keras.layers.embeddings import Embedding
from keras.layers import Input, Dense
from keras.models import Model

import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
import os
import csv
import pandas as pd
import io
from skimage import io
import numpy as np

import re

from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical
from keras.models import Sequential, load_model
from keras.layers import Dense, Embedding, LSTM, Flatten, Dropout, Conv1D, Conv2D
from keras import optimizers
from keras.models import load_model
import json, argparse, os
import re
import io
import sys


import re
import pandas as pd
# import emoji
from sklearn.model_selection import train_test_split
# from autocorrect import spell
from collections import defaultdict
import string
import nltk
# from nltk.corpus import stopwords
# nltk.download('stopwords')

Using TensorFlow backend.


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


In [5]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [6]:
!ls "/content/drive/My Drive"

 A2_SarahShams_i150097.ipynb	   SE
 AI				   Snapchat-88614669.jpg
 AItest.csv			   ss
 Assignment+Not+1+_search_.ipynb   Uni
'Colab Notebooks'		   Untitled0.ipynb
 DEEP				   winequality-red.csv
 FYP				   winequality-white.csv


In [0]:
def extract_pp(filename,fformat = "lxml"):
    """
      Given a file name for baby.html, returns a list starting with the year string
      followed by the name-rank strings in alphabetical order.
      ['2006', 'Aaliyah 91', Aaron 57', 'Abagail 895', ' ...]
    """
    name = []
    with open(filename) as f:
        website_html  = f.read()
    html = bs4.BeautifulSoup( website_html,fformat)
        
    return html
    

In [8]:
import os

path = "/content/drive/My Drive/FYP/Final Year Project Code/annotations"
dirs = os.listdir( path )
dirs[:2]

['1017_sci-news.com.csv', '1034_aol.com.csv']

In [9]:
from os import listdir
from os.path import isfile, join
onlyfiles = [f for f in listdir("/content/drive/My Drive/FYP/Final Year Project Code/sanitized_policies") if isfile(join("/content/drive/My Drive/FYP/Final Year Project Code/sanitized_policies", f))]
onlyfiles[:2]

['1017_sci-news.com.html', '105_amazon.com.html']

In [0]:
from nltk import word_tokenize

In [0]:
# !ls "/content/drive/My Drive/FYP/Final Year Project Code/sanitized_policies"

In [12]:
directory = dict()
for dir in dirs:
  directory[re.sub("[\d]+_|.csv","",dir)] = "/content/drive/My Drive/FYP/Final Year Project Code/annotations/"+dir
directory[list(directory.keys())[0]]

'/content/drive/My Drive/FYP/Final Year Project Code/annotations/1017_sci-news.com.csv'

In [0]:
from collections import defaultdict

In [0]:
defineCategories = str(extract_pp ('/content/drive/My Drive/FYP/Final Year Project Code/categories-july30.xml',"xml"))

In [15]:
defineCategories

'<?xml version="1.0" encoding="utf-8"?>\n<categories xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="annotation.xsd">\n<version>20151115-01</version>\n<category>\n<name>First Party Collection/Use</name>\n<description> Privacy practice describing data collection or data use by the company/organization owning the website or mobile app.</description>\n<attributes>\n<attribute color="#999999" default="Does" optional="true">\n<name>Does/Does Not</name>\n<description>Use this optional attribute to denote if the policy explicitly states that something is NOT done. Defaults to Does.</description>\n<values>\n<value>\n<name>Does</name>\n<description>The first party does engage in the described practice.</description>\n</value>\n<value>\n<name>Does Not</name>\n<description>The first party does not engage in the described practice.</description>\n</value>\n</values>\n</attribute>\n<attribute color="#CCCCCC" default="not-selected" optional=

In [0]:
from bs4 import BeautifulSoup
import urllib.request

# source = urllib.request.urlopen('/content/drive/My Drive/FYP/Final Year Project Code/categories-july30.xml').read()
soup = BeautifulSoup(str(defineCategories),'lxml')


In [0]:
from collections import defaultdict


In [0]:
categoryList = []
attribute_n_values = defaultdict (lambda:defaultdict(lambda:""))

In [0]:
# print (len(soup.attributes))
for c in soup.categories:
  Vcategory = BeautifulSoup(str(c),'lxml')
#   print (len(Vcategory.category))
  if (Vcategory.category is not None):
    for k in Vcategory.category:
      l = str(k).replace("<name>","<cname>")
      l = str(l).replace("</name>","</cname>")
      attribute = BeautifulSoup(str(l),'lxml')
      
#       print (re.sub("<cname>|</cname>","",str(attribute.cname)))
      if (attribute.attributes is not None):
        for i in (attribute.attributes):
        #   print (str(i))
          l = str(i).replace("<cname>","<aname>")
          l = str(l).replace("</cname>","</aname>")
          attr = BeautifulSoup(str(l),'lxml')
    #       print (len(attr))
#           if (attr.aname is not None) :   
            
          if len(attr)>0:
            if (attr.values is not None):
              for j in attr.values:
    #             print (j,"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\")
                l = str(j).replace("<aname>","<vname>")
                l = str(l).replace("</aname>","</vname>")
                attr_ValueName = BeautifulSoup(str(l),'lxml')

                if (attr_ValueName.vname is not None):
                  attribute_name = re.sub("<aname>|</aname>","",str(attr.aname))
#                   print ("Attribute Name:\t", re.sub("<aname>|</aname>","",str(attr.aname)))
                  attribute_value = re.sub("<vname>|</vname>","",str(attr_ValueName.vname))
#                   print ("Attribute Value:\t",re.sub("<vname>|</vname>","",str(attr_ValueName.vname)))
                  attribute_n_values[attribute_name][attribute_value] = ""

              
              
              
              
#   #               for l in attr_ValueName.value:
                
#                 attr_Value = BeautifulSoup(str(l),'lxml')
#                 if (attr_Value.vname is not None):
#                   print (str(attr_Value.vname))
#       print (str(attr_Value.ValueName))
#     print (str(j))
# soup = BeautifulSoup(str(attr_str),'lxml')
# soup.value

In [0]:
import json

In [0]:
attributeNames = list(attribute_n_values.keys())
# attributeNames

In [0]:
# import ipynb
# from ipynb.fs.full.common import *
# from IPython import get_ipython
# from nbformat import current
# from IPython.common import *
    
def clean(txt):
  
  s = re.sub ("<br>| <br>| <br/> <br/>|\. <br/> <br/>",". ",str(txt))
  s = re.sub(";|</li>[ ]*</ul>|\([i|v|x]+\)","",str(s))
  s = re.sub("<\w*>|<\w*\/>|<\/\w*>|\d*","",str(s))
  s = re.sub("[^ A-Za-z\.]","",s)
  return s
    

In [23]:
text_list = []
privacy115_SegmentID = [] # appends all the SI of a privacy document 
labeltotal = np.zeros ((10,))
for d in range(len(dirs)):
  print (onlyfiles[d])#,directory[re.sub("[\d]+_|.html","",onlyfiles[d])])
  with open(directory[re.sub("[\d]+_|.html","",onlyfiles[d])], 'r') as csvfile:
      spamreader = csv.reader(csvfile)
      t=[]
      for row in spamreader:
          t.append(row)
      SI = defaultdict (lambda: "") # keys is the segment ID : values are the corresponding labels and count
      
      
      for i in range(len(t)):
        selectedSentence = json.loads(np.array(t)[i,6])
        for k in selectedSentence.keys():
#           print (selectedSentence[k].keys())
#           print (selectedSentence)
          if ("selectedText" in selectedSentence[k].keys()):
            sen = selectedSentence[k]["selectedText"]
            if (sen.lower() not in " not-selected " and sen.lower() not in " not selected " and sen.lower() not in " unspecified " and sen.lower() not in  " null " ):

              attribute_n_values[k][selectedSentence[k]["value"]] += clean(selectedSentence[k]["selectedText"]) + " | "
              text_list.append( clean(selectedSentence[k]["selectedText"]).split() )


1017_sci-news.com.html
105_amazon.com.html
1028_redorbit.com.html
1050_honda.com.html
1034_aol.com.html
1070_wnep.com.html
1106_allstate.com.html
1089_freep.com.html
1099_enthusiastnetwork.com.html
1083_highgearmedia.com.html
1164_acbj.com.html
1224_austincc.edu.html
1252_cincymuseum.org.html
1221_gwdocs.com.html
1206_dcccd.edu.html
1259_fool.com.html
1205_opensecrets.org.html
1261_zacks.com.html
1300_bankofamerica.com.html
1264_citizen.org.html
1306_chasepaymentech.com.html
133_fortune.com.html
1360_thehill.com.html
135_instagram.com.html
1468_rockstargames.com.html
1470_steampowered.com.html
1419_miaminewtimes.com.html
144_style.com.html
1498_ticketmaster.com.html
1361_yahoo.com.html
1510_jibjab.com.html
1582_msn.com.html
1539_geocaching.com.html
1545_taylorswift.com.html
1610_post-gazette.com.html
1637_dailyillini.com.html
1618_sltrib.com.html
164_adweek.com.html
1666_wsmv.com.html
1636_sidearmsports.com.html
1673_tulsaworld.com.html
1683_dailynews.com.html
1694_lids.com.html
1703_s

In [0]:
DROPOUT = None

In [0]:
def make_model(mname,shape, num):
  model = Sequential(name = mname)

  model.add(Conv1D( 200,3, activation='relu',input_shape=shape,kernel_initializer='glorot_uniform') )

  model.add(MaxPooling1D(pool_size=2))
  model.add(Conv1D(150,3, activation='relu'))
  model.add(MaxPooling1D(pool_size=2))
#   model.add(Conv1D(100,3, activation='relu'))
#   model.add(MaxPooling1D(pool_size=2))

  model.add(Dense(50, activation = "relu"))
  model.add(Flatten())
  model.add(Dense(num, activation = "sigmoid"))
#   embeddingLayer = Embedding(shape[0],
#                                   shape[1],
#                                   weights=[embeddingMatrix],
#                                   input_length=30,
#                                   trainable=False)

# #     model = Sequential()
#   model.add(embeddingLayer)
    
#   model.add(LSTM(300,dropout=DROPOUT,return_sequences=True))
#   model.add(LSTM(300,dropout=DROPOUT, return_sequences=True))
#   model.add(LSTM(300,dropout=DROPOUT, return_sequences=True))
#   model.add(LSTM(300, dropout=DROPOUT))
#   model.add(Dropout(DROPOUT))
#   model.add(Dense(40))
#   model.add(Dropout(DROPOUT))

  return model


In [0]:
from gensim.models import Word2Vec
#model = Word2Vec.load('/content/drive/My Drive/FYP/Final Year Project Code/PP_word2vec_new.bin')
import pandas as pd
import numpy as np
import nltk
import re
import bs4
import gensim.downloader as api

In [0]:
# from gensim.models import Word2Vec
# w2v = Word2Vec.load('/content/drive/My Drive/FYP/Final Year Project Code/PP_word2vec_new.bin')

In [0]:
w2v = Word2Vec(text_list, min_count=1, compute_loss=True, size=100)

# # summarize the loaded model
# print(model)

In [0]:
w2v = Word2Vec.load('/content/drive/My Drive/FYP/Final Year Project Code/PP_attribute_word2vec_new.bin')

In [0]:
# for count in range(0,2):
#     w2v.train(text_list,total_examples=len(text_list), epochs=500, compute_loss=True,start_alpha=0.1)
#     print (w2v.get_latest_training_loss())

13010344.0
10013713.0


In [0]:
# save model
w2v.save('/content/drive/My Drive/FYP/Final Year Project Code/PP_attribute_word2vec_new.bin')
# # load model


In [29]:
len(attribute_n_values.keys())

22

In [0]:
# len(models)

In [0]:
def s2V(s):
  
  sent = np.zeros((100,))
  
  for w in s.split() :
#     #print (np.array(df[Lemmatization(w)]).shape)
#     print (sent)
#     print (model[w])
    sent += np.array(w2v[w])
  
  return np.array(sent)

In [0]:
labls_array = []
attribute_n_values_index = defaultdict (lambda:[])


for k in attributeNames:
  attribute_n_values_index[k] = list(attribute_n_values[k].keys())
    

In [0]:
# w2v["endeavor"]

In [0]:
# !pip install ipynb

In [35]:

secVectors = []

for k in attributeNames:
  for kk in attribute_n_values_index[k]:
    for sen in attribute_n_values[k][kk].split("|"):
      
#         print (type(sen),sen, sen in ' null ', cleanData(sen))# upr se theek krna hai
#         break
#         print(sen, clean(sen))
        secVectors.append(s2V(clean(sen)))
secVectors = np.array(secVectors)    

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  if __name__ == '__main__':


In [36]:
secVectors.shape

(77988, 100)

In [0]:
models=[]
sgd = keras.optimizers.SGD(lr = 0.05)
adam = keras.optimizers.Adam(lr=0.1)
  
for i in range(len(attribute_n_values.keys())):
  
  models.append(make_model(list(attribute_n_values.keys())[i],(np.shape(secVectors)[1:][0],1),len(attribute_n_values[list(attribute_n_values.keys())[i]].keys())+1 ))
  models[i].compile(optimizer=adam, loss='mean_squared_error', metrics=['acc'])


In [38]:
 for k in attributeNames:
    for kk in attribute_n_values_index[k]:
      print (len(attribute_n_values[k][kk].split("|")))

6571
658
1871
2235
314
3237
308
39
101
77
50
368
166
736
1523
2093
1417
256
419
503
258
1782
522
464
139
1233
217
86
782
1838
590
96
2780
602
2365
113
1974
1471
1668
1510
1620
826
589
550
258
504
954
430
141
1060
314
368
724
1535
497
415
233
236
553
343
314
1210
485
202
195
293
638
299
138
2390
1512
417
78
136
86
167
3451
423
445
183
332
177
10
119
2
381
20
71
32
69
41
299
30
71
52
50
121
33
103
42
26
132
95
48
21
41
5
7
30
40
136
37
54
137
11
38
67
396
129
13
22
218
16
15
210
23
175
119
102
30
56
70
13
24
40
13
95
2
4
76
9
4
200
59
126
520
37
1376
789
648
735


In [0]:
def stratifiedSampling (attribute_n_values, attr,attributeNames, attribute_n_values_index):
  halfdataset = 0
  total_no_values = 0
  labls_array=[]
  
  for attribute in attributeNames:
    for value in attribute_n_values_index[attribute]:
      if (attribute == attr):
        halfdataset+=len(attribute_n_values[attribute][value].split("|"))
      total_no_values+=len(attribute_n_values[attribute][value].split("|"))
#   print (halfdataset)  
#   total_no_values = sum(len(numofvalues) for numofvalues in attribute_n_values_index.items())
  
  new_data=[]
  
  percentage_of_each_value = halfdataset/float(total_no_values-halfdataset)
  print ("Total_no_values: ", total_no_values, "\nHalfDataset: ", halfdataset,"\nPercentage: ",percentage_of_each_value)
  i=0
  for attribute in attributeNames:
    for value in attribute_n_values_index[attribute]:
      
      if attr == attribute:
        for sen in attribute_n_values[attribute][value].split("|"):
          labls= np.zeros((len(attribute_n_values_index[attr])+1, ))
          new_data.append(s2V(clean(sen)))
          labls[np.where(np.array(attribute_n_values_index[attribute]) == value)[0][0]] = 1
          labls[-1] = 1
          labls_array.append(labls)
      else:
        for sen_len in range(np.ceil(len(attribute_n_values[attribute][value].split("|"))*percentage_of_each_value).astype(np.int32)):
#           print ("length: ",np.ceil(len(attribute_n_values[attribute][value].split("|"))*percentage_of_each_value).astype(np.int32))
          new_data.append(s2V(clean(attribute_n_values[attribute][value].split("|")[sen_len])))
          labls= np.zeros((len(attribute_n_values_index[attr])+1, ))
          labls_array.append(labls)
  
  new_data = np.array(new_data)
  labls_array = np.array(labls_array)
  print (np.shape(labls_array), np.shape(new_data) )
  s = np.arange((new_data).shape[0])
  np.random.shuffle(s)
  labls_array = labls_array[s]
  new_data = new_data[s]
  return new_data, labls_array
      
        
      

In [0]:
# def attr_model(secVector,attr):
    
#   labls_array=np.zeros((secVector.shape[0],len(attribute_n_values_index[attr])+1))
#   i = 0
#   for k in attributeNames:
#     for kk in attribute_n_values_index[k]:
#       for sen in attribute_n_values[k][kk].split("|"):
# #         labls = np.zeros((len(attribute_n_values_index[k])+1,))
# #         print (labls.shape)
# #         print (attribute_n_values_index[k],kk)
# #         print (np.where(np.array(attribute_n_values_index[k]) == kk)[0][0])  
# #         labls = np.zeros((len(attribute_n_values_index[attr])+1,))
        
    
#         if k == attr:
#           labls_array[i][np.where(np.array(attribute_n_values_index[k]) == kk)[0][0]] = 1
#           labls_array[i][-1] = 1
        
# #         labls_array = labls
# #         print (np.shape(labls_array))
# #         break
# #       break
# #     break
#         i+=1
#   print (np.shape(labls_array))
#   return labls_array





In [0]:
# print (np.shape())

In [0]:
def shuffle(arr):
#   secVectors = np.array(secVectors).reshape((4734, 100, 1))
  s = np.arange((arr).shape[0])
  np.random.shuffle(s)
  return s

In [69]:
for i in range(len(models)):
  print ("\n ------------------------------------------- ",attributeNames[i]," ------------------------------------------- \n")
  
  secVectors, labls = stratifiedSampling (attribute_n_values, attributeNames[i],attributeNames, attribute_n_values_index)
#   break
  trainsize= int(len(labls)*0.7)
#   print (models[i].summary(),np.shape(labls))
#   print ((labls)[:30])
#   break
  models[i].fit(x = np.copy(np.expand_dims(secVectors, axis=-1))[:trainsize],y= np.copy(labls)[:trainsize], batch_size=200, epochs=10,shuffle=True)
#   p = models[i].predict(np.copy(np.expand_dims(secVectors, axis=-1)[:trainsize]))
#   theek = 0
#   for i in range(len(p)):
#     if np.all(np.array(p[i]) ==np.copy(labls)[i]):
#       print (np.array(p[i]) ,np.copy(labls)[i])
#       theek +=1
#       break

#   print (theek)
#   break


 -------------------------------------------  Does/Does Not  ------------------------------------------- 

Total_no_values:  77988 
HalfDataset:  7229 
Percentage:  0.1021636823584279


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  if __name__ == '__main__':


(14539, 3) (14539, 100)
Epoch 1/10
10177/10177 [==============================] - 1s 100us/step - loss: 0.3636 - acc: 0.9546
Epoch 2/10
10177/10177 [==============================] - 1s 89us/step - loss: 0.3636 - acc: 0.9546
Epoch 3/10
10177/10177 [==============================] - 1s 118us/step - loss: 0.3636 - acc: 0.9546
Epoch 4/10
10177/10177 [==============================] - 1s 90us/step - loss: 0.3636 - acc: 0.9546
Epoch 5/10
10177/10177 [==============================] - 1s 89us/step - loss: 0.3636 - acc: 0.9546
Epoch 6/10
10177/10177 [==============================] - 1s 90us/step - loss: 0.3636 - acc: 0.9546
Epoch 7/10
10177/10177 [==============================] - 1s 89us/step - loss: 0.3636 - acc: 0.9546
Epoch 8/10
10177/10177 [==============================] - 1s 90us/step - loss: 0.3636 - acc: 0.9546
Epoch 9/10
10177/10177 [==============================] - 1s 89us/step - loss: 0.3636 - acc: 0.9546
Epoch 10/10
10177/10177 [==============================] - 1s 89us/step - 

In [70]:
# for k in attributeNames:
#   for kk in attribute_n_values_index[k]:
sen =  attribute_n_values[attributeNames[0]][attribute_n_values_index[attributeNames[0]][0]].split("|")[0]
# sen = np.expand_dims(np.expand_dims(s2V(sen), axis=0), axis=-1)
sen = np.expand_dims(np.expand_dims(secVectors[0], axis=0), axis=-1)
print (attributeNames[-3],"<" , attribute_n_values_index[attributeNames[-3]][-1],"<" ,sen.shape)
for i in range(len(models)):
  
  
  print (models[i].predict(sen))
      

Do Not Track policy < Other < (1, 100, 1)
[[0. 0. 0.]]
[[0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]]


In [0]:
# 